package _teamlaunchers;

public enum BuildOrderMessaging {
    BuildBeaverBuilder,
    BuildBeaverMiner,
    BuildBasher,
    BuildCommander,
    BuildComputer,
    BuildDrone,
    BuildScoutingDrone,
    BuildSupplyDrone,
    BuildSearchAndDestroyDrone,
    BuildLauncher,
    BuildMiner,
    BuildSoldier,
    BuildTank,
    BuildAerospaceLab,
    BuildBaracks,
    BuildHelipad,
    BuildMinerFactory,
    BuildTankFactory,
    BuildTechnologyInstitute,
    BuildTrainingField,
    BuildSupplyDepot,
    BuildMiningBaracks,
    BuildDefensiveSoldier,
    BuildDefensiveTank,
    BuildDefensiveBasher,
    BuildMiningAeroSpaceLab,
    BuildHarrassSoldier,
    BuildHarrassBasher,
    BuildHarrassTank,
    // this should be last entry
    DoneBuilding
}
